//+------------------------------------------------------------------+
//|                                           DynamicGrid_XAUUSD.mq5 |
//|                               Generated by Strategi Trading (AI) |
//+------------------------------------------------------------------+
#property copyright "Strategi Trading"
#property version   "1.00"

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>

//--- Input Parameters
input double   InpStartLot          = 0.01;      // Initial Lot Size
input double   InpLotMultiplier     = 1.25;      // Soft Martingale Multiplier
input double   InpTakeProfitPips    = 1.0;       // Take Profit (in Pips)
input double   InpMaxDistIntra      = 1.50;      // Max Averaging Intra-Candle (Pips)
input double   InpMinDistInter      = 0.50;      // Min Averaging Inter-Candle (Pips)
input ulong    InpMagicNumber       = 777888;    // Magic Number

CTrade         trade;
CPositionInfo  posInfo;

//--- Global Variables for tracking
datetime       lastOrderCandleTime  = 0;
double         lastOrderPrice       = 0.0;
double         lastOrderLot         = 0.0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   trade.SetExpertMagicNumber(InpMagicNumber);
   Print("EA Dynamic Grid Initialized.");
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // Hitung jumlah posisi Buy yang sedang terbuka
   int totalBuyPositions = 0;
   double totalVolume = 0.0;
   double weightedPrice = 0.0;
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber && posInfo.PositionType() == POSITION_TYPE_BUY)
           {
            totalBuyPositions++;
            totalVolume += posInfo.Volume();
            weightedPrice += posInfo.PriceOpen() * posInfo.Volume();
           }
        }
     }

   // 1. Logika Entri Pertama (Jika tidak ada posisi)
   if(totalBuyPositions == 0)
     {
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      if(trade.Buy(InpStartLot, _Symbol, ask, 0, 0, "Initial Entry"))
        {
         UpdateLastOrderInfo();
        }
      return;
     }

   // 2. Logika Averaging Grid (Jika ada posisi yang floating)
   if(totalBuyPositions > 0)
     {
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      datetime currentCandleTime = iTime(_Symbol, PERIOD_CURRENT, 0);
      
      // Konversi Pips ke Point (Asumsi standar: 1 Pip = 10 Points)
      double pipsToPoint = 10 * _Point; 
      
      double distanceToLastOrder = (lastOrderPrice - ask) / pipsToPoint; // Hitung jarak turun dalam pips
      
      bool shouldOpenAveraging = false;

      // Cek Kondisi Intra-Candle (Di dalam candle yang sama)
      if(currentCandleTime == lastOrderCandleTime)
        {
         if(distanceToLastOrder >= InpMaxDistIntra) // Harga turun sejauh Max 1.50 pips
           {
            shouldOpenAveraging = true;
           }
        }
      // Cek Kondisi Inter-Candle (Ganti candle baru)
      else if(currentCandleTime != lastOrderCandleTime)
        {
         if(distanceToLastOrder >= InpMinDistInter) // Harga turun minimal 0.50 pips di candle baru
           {
            shouldOpenAveraging = true;
           }
        }

      // Eksekusi Order Averaging
      if(shouldOpenAveraging)
        {
         // Hitung Lot Martingale 1.25x dan bulatkan
         double nextLot = NormalizeDouble(lastOrderLot * InpLotMultiplier, 2); 
         
         if(trade.Buy(nextLot, _Symbol, ask, 0, 0, "Averaging Layer"))
           {
            UpdateLastOrderInfo();
            UpdateTakeProfit(totalVolume, weightedPrice); // Update TP gabungan
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Fungsi untuk Update Data Order Terakhir                          |
//+------------------------------------------------------------------+
void UpdateLastOrderInfo()
  {
   // Mencari posisi terakhir yang dibuka
   if(PositionSelect(_Symbol)) 
     {
      lastOrderPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      lastOrderLot = PositionGetDouble(POSITION_VOLUME);
      lastOrderCandleTime = iTime(_Symbol, PERIOD_CURRENT, 0);
     }
  }

//+------------------------------------------------------------------+
//| Fungsi untuk Update Take Profit Gabungan (Average TP)            |
//+------------------------------------------------------------------+
void UpdateTakeProfit(double totalVol, double weightedPrc)
  {
   // Hitung BEP (Break Even Point) rata-rata
   double avgPrice = weightedPrc / totalVol;
   
   // Konversi TP Pips ke Point
   double tpPoints = InpTakeProfitPips * 10 * _Point;
   
   // Target TP = Harga Rata-rata + TP Pips
   double targetTP = NormalizeDouble(avgPrice + tpPoints, _Digits);

   // Modifikasi TP semua posisi Buy ke titik yang sama
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber && posInfo.PositionType() == POSITION_TYPE_BUY)
           {
            if(posInfo.TakeProfit() != targetTP)
              {
               trade.PositionModify(posInfo.Ticket(), posInfo.StopLoss(), targetTP);
              }
           }
        }
     }
  }
